name: hotel_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_route: ^7.8.0
  bloc: ^8.1.1
  carousel_slider: ^4.2.1
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.0.3
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  mockito: ^5.4.2
  mocktail: ^1.0.0
  rxdart: ^0.27.7
  shimmer: ^3.0.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.4
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF-Pro-Display-Light.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Black.otf
        - asset: assets/fonts/SF-Pro-Display-BlackItalic.otf
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
        - asset: assets/fonts/SF-Pro-Display-HeavyItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Light.otf
        - asset: assets/fonts/SF-Pro-Display-LightItalic.otf
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
        - asset: assets/fonts/SF-Pro-Display-SemiBold.otf
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
        - asset: assets/fonts/SF-Pro-Display-ThinItalic.otf